"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";

type Product = { id?: string; code: string; name: string; brand: string; category: string; net_quantity?: string; mrp?: string; manufacturer?: string; country_of_origin?: string; customer_care?: string; packed_on?: string; expiry?: string; image_url?: string };
type Finding = { label: string; detail: string; passed: boolean };

const demo: Product = {
  code: "8901234567890", name: "Classic Oats", brand: "Field & Fork", category: "Food & beverage", net_quantity: "500 g", mrp: "₹210 (incl. all taxes)", manufacturer: "Field & Fork Foods Pvt. Ltd., Bengaluru 560 038", country_of_origin: "India", customer_care: "care@fieldandfork.in · 1800 222 910", packed_on: "Aug 2026", expiry: "Best before 12 months from packing"
};

function Icon({ name, size = 20 }: { name: "scan" | "shield" | "search" | "upload" | "arrow" | "close" | "check" | "warn"; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    scan: <><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><path d="M7 12h10M7 9h10M7 15h10"/></>,
    shield: <path d="M12 3 5 6v5c0 4.5 3 8.1 7 10 4-1.9 7-5.5 7-10V6l-7-3Z"/>,
    search: <><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></>, upload: <><path d="M12 16V4M8 8l4-4 4 4"/><path d="M5 14v5h14v-5"/></>, arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>, check: <path d="m5 12 4 4L19 6"/>, warn: <><path d="M12 3 2.5 20h19L12 3Z"/><path d="M12 9v4M12 17h.01"/></>
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function compliance(product: Product): Finding[] {
  const declarations: [string, string | undefined][] = [
    ["Name of commodity", product.name], ["Net quantity", product.net_quantity], ["Maximum retail price", product.mrp], ["Manufacturer / packer details", product.manufacturer], ["Country of origin", product.country_of_origin], ["Consumer care details", product.customer_care], ["Month and year of packing", product.packed_on]
  ];
  return declarations.map(([label, value]) => ({ label, detail: value ? String(value) : "Not found on product record", passed: Boolean(value) }));
}

export default function Home() {
  const [query, setQuery] = useState(""); const [product, setProduct] = useState<Product | null>(null); const [loading, setLoading] = useState(false); const [scanOpen, setScanOpen] = useState(false); const [cameraError, setCameraError] = useState("");
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const detectorRef = useRef<number | null>(null);
  const findings = product ? compliance(product) : []; const passed = findings.filter(f => f.passed).length;
  const stopCamera = () => { streamRef.current?.getTracks().forEach(t => t.stop()); streamRef.current = null; if (detectorRef.current) cancelAnimationFrame(detectorRef.current); };
  const lookup = async (value = query) => { if (!value.trim()) return; setLoading(true); try { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY; if (!url || !key) { setProduct(demo); return; } const response = await fetch(`${url}/rest/v1/products?code=eq.${encodeURIComponent(value.trim())}&select=*`, { headers: { apikey: key, Authorization: `Bearer ${key}` } }); const data = await response.json(); setProduct(data?.[0] || (value.trim() === demo.code ? demo : null)); } catch { setProduct(value.trim() === demo.code ? demo : null); } finally { setLoading(false); } };
  const startCamera = async () => { setScanOpen(true); setCameraError(""); try { if (!("BarcodeDetector" in window)) throw new Error("Camera scanning isn’t supported by this browser. Upload a label image or enter the code instead."); const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); const Detector = (window as unknown as { BarcodeDetector: new (o: { formats: string[] }) => { detect: (v: HTMLVideoElement) => Promise<{ rawValue: string }[]> } }).BarcodeDetector; const detector = new Detector({ formats: ["qr_code", "ean_13", "ean_8", "code_128", "upc_a"] }); const read = async () => { if (!videoRef.current || !streamRef.current) return; const codes = await detector.detect(videoRef.current); if (codes[0]?.rawValue) { stopCamera(); setScanOpen(false); setQuery(codes[0].rawValue); lookup(codes[0].rawValue); return; } detectorRef.current = requestAnimationFrame(read); }; read(); } } catch (e) { setCameraError(e instanceof Error ? e.message : "Could not access camera."); } };
  useEffect(() => () => stopCamera(), []);
  const fromImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { if (!("BarcodeDetector" in window)) throw new Error("Image decoding is not supported in this browser."); const bitmap = await createImageBitmap(file); const Detector = (window as unknown as { BarcodeDetector: new (o: { formats: string[] }) => { detect: (v: ImageBitmap) => Promise<{ rawValue: string }[]> } }).BarcodeDetector; const codes = await new Detector({ formats: ["qr_code", "ean_13", "ean_8", "code_128", "upc_a"] }).detect(bitmap); if (!codes[0]) throw new Error("No barcode or QR code found in that image."); setQuery(codes[0].rawValue); lookup(codes[0].rawValue); } catch (e) { alert(e instanceof Error ? e.message : "Unable to scan image."); } };
  return <main><header><a className="logo" href="#top"><span>label</span>lab<i>.</i></a><nav><a href="#how">How it works</a><a href="#law">The law</a><a href="#about">About</a></nav><button className="nav-cta" onClick={startCamera}><Icon name="scan" size={17}/> Scan a label</button></header>
    <section className="hero" id="top"><div className="eyebrow"><span></span> INDIAN CONSUMER PROTECTION</div><h1>Know what’s<br/><em>on the label.</em></h1><p>Scan any barcode or QR code to instantly check product details against India’s Legal Metrology rules.</p><div className="searchbox"><Icon name="search"/><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && lookup()} placeholder="Enter barcode or product code"/><button onClick={() => lookup()} disabled={loading}>{loading ? "Checking…" : <><span>Check label</span><Icon name="arrow" size={17}/></>}</button></div><div className="hero-actions"><button className="scan-link" onClick={startCamera}><Icon name="scan"/> Scan with camera</button><label className="upload-link"><Icon name="upload"/> Upload a label image<input type="file" accept="image/*" onChange={fromImage}/></label></div><p className="tiny">No account needed. We never store your scans.</p></section>
    <section className="trust"><div><Icon name="shield"/><span>Built around the<br/><b>Legal Metrology Act, 2009</b></span></div><div className="trust-copy">Clear, independent checks for the mandatory declarations on packaged goods in India.</div><a href="#law">Learn about the rules <Icon name="arrow" size={16}/></a></section>
    {product && <section className="result" aria-live="polite"><div className="result-top"><div><span className="kicker">SCAN RESULT · {product.code}</span><h2>{product.name}</h2><p>{product.brand} <i>·</i> {product.category}</p></div><div className={`score ${passed === findings.length ? "good" : "attention"}`}><strong>{passed}<small>/{findings.length}</small></strong><span>requirements present</span></div></div><div className="verdict"><div className={passed === findings.length ? "round good" : "round attention"}>{passed === findings.length ? <Icon name="check"/> : <Icon name="warn"/>}</div><div><b>{passed === findings.length ? "Label information looks complete" : "This label may need attention"}</b><p>{passed === findings.length ? "All core declarations required for a pre-packaged commodity were found." : `${findings.length - passed} core declaration${findings.length - passed > 1 ? "s were" : " was"} not found in the product record.`}</p></div></div><div className="findings">{findings.map(f => <div className="finding" key={f.label}><div className={f.passed ? "status yes" : "status no"}>{f.passed ? <Icon name="check" size={15}/> : <Icon name="warn" size={15}/>}</div><div><b>{f.label}</b><p>{f.detail}</p></div></div>)}</div><p className="disclaimer">This is an informational screening, not a legal determination. Requirements may vary by product category.</p></section>}
    {!product && query && !loading && <p className="notfound">No product record found. Try the demo barcode <button onClick={() => { setQuery(demo.code); lookup(demo.code); }}>8901234567890</button>.</p>}
    <section className="steps" id="how"><span className="kicker">SIMPLE BY DESIGN</span><h2>From code to clarity<br/>in seconds.</h2><div className="step-grid"><article><span>01</span><Icon name="scan"/><h3>Scan the code</h3><p>Use your camera or upload a clear image of any barcode or QR code.</p></article><article><span>02</span><Icon name="search"/><h3>We read the label</h3><p>LabelLab matches the product and checks every mandatory declaration.</p></article><article><span>03</span><Icon name="shield"/><h3>Know where it stands</h3><p>Get a calm, plain-English summary of what’s present and what’s missing.</p></article></div></section>
    <section className="law" id="law"><div><span className="kicker">WHY IT MATTERS</span><h2>Labels are a consumer right.</h2><p>India’s Legal Metrology framework requires pre-packaged goods to clearly declare key information—so consumers can make informed choices.</p></div><div className="law-card"><span>THE BASICS</span><ul><li>What the product is</li><li>How much you’re getting</li><li>The maximum retail price</li><li>Who made or packed it</li><li>Where it was made</li></ul><p>Based on the Legal Metrology Act, 2009 and the Packaged Commodities Rules, 2011.</p></div></section>
    <footer id="about"><a className="logo" href="#top"><span>label</span>lab<i>.</i></a><p>Better labels. More informed choices.</p><span>© 2026 LabelLab · Made for India</span></footer>
    {scanOpen && <div className="modal"><div className="scanner"><button className="close" onClick={() => { stopCamera(); setScanOpen(false); }}><Icon name="close"/></button><span className="kicker">POINT CAMERA AT CODE</span><h2>Scan a label</h2><div className="video-wrap">{cameraError ? <div className="camera-error"><Icon name="warn"/><p>{cameraError}</p></div> : <video ref={videoRef} muted playsInline/>}<div className="frame"></div></div><p>Hold the barcode or QR code inside the frame.</p></div></div>}
  </main>;
}
